### ISSUE TITLE
Link colour makes it look like I’ve visited pages already

### ISSUE THREAD

**Issue by robinwhittleton** [openregister/www.openregister.org#6]
The link colours are back to front to default usage; purple for normal and blue for visited. E.g. in this screenshot I’ve visited the GDS blog but not the Government data blog. Could this be swapped?

<img width="723" alt="Screenshot demonstrating the backwards colours" src="https://user-images.githubusercontent.com/7414/29862239-527765d4-8d6c-11e7-9032-bb014fe333b1.png">

**Comment by robinwhittleton** [comment]
Of course, I could just do a PR: https://github.com/openregister/www.openregister.org/pull/7

**Comment by dankmitchell** [comment]
Resolved
